version: '3'
services:
  master:
    build: .
    container_name: hadoop-master
    hostname: master
    environment:
      - NODE_TYPE=${NODE_TYPE_MASTER}
      - HADOOP_HOME=${HADOOP_HOME}
      - HIVE_HOME=${HIVE_HOME}
      - JAVA_HOME=${JAVA_HOME}
      - HDFS_NAMENODE_USER=${HDFS_NAMENODE_USER}
      - HDFS_DATANODE_USER=${HDFS_DATANODE_USER}
      - HDFS_SECONDARYNAMENODE_USER=${HDFS_SECONDARYNAMENODE_USER}
      - YARN_RESOURCEMANAGER_USER=${YARN_RESOURCEMANAGER_USER}
      - YARN_NODEMANAGER_USER=${YARN_NODEMANAGER_USER}
    networks:
      hadoop-net:
        aliases:
          - master
    ports:
      - "9870:9870"    # HDFS Web UI
      - "8088:8088"    # YARN Resource Manager
      - "10000:10000"  # HiveServer2 Thrift port
      - "10002:10002"  # Optional Hive Web Interface or additional port
    command: >
      sh -c "service ssh start &&
            if [ -f $HADOOP_HOME/sbin/start-dfs.sh ]; then
              if [ ! -d /tmp/hadoop-root/dfs/name ]; then
                $HADOOP_HOME/bin/hdfs namenode -format;
              fi &&
              $HADOOP_HOME/sbin/start-dfs.sh &&
              $HADOOP_HOME/sbin/start-yarn.sh &&
              # สร้าง directories สำหรับ Hive
              $HADOOP_HOME/bin/hdfs dfs -mkdir -p /tmp &&
              $HADOOP_HOME/bin/hdfs dfs -chmod g+w /tmp &&
              $HADOOP_HOME/bin/hdfs dfs -mkdir -p /user/hive/warehouse &&
              $HADOOP_HOME/bin/hdfs dfs -chmod g+w /user/hive/warehouse
            else
              echo 'Hadoop start-dfs.sh not found in $HADOOP_HOME/sbin';
            fi &&
            tail -f /dev/null"


  worker1:
    build: .
    container_name: hadoop-worker1
    hostname: worker1
    environment:
      - NODE_TYPE=${NODE_TYPE_WORKER}
      - HADOOP_HOME=${HADOOP_HOME}
      - JAVA_HOME=${JAVA_HOME}
    networks:
      hadoop-net:
        aliases:
          - worker1
    depends_on:
      - master
    command: >
      sh -c "service ssh start &&
             $HADOOP_HOME/sbin/hadoop-daemon.sh start datanode &&
             $HADOOP_HOME/sbin/yarn-daemon.sh start nodemanager &&
             tail -f /dev/null"

  worker2:
    build: .
    container_name: hadoop-worker2
    hostname: worker2
    environment:
      - NODE_TYPE=${NODE_TYPE_WORKER}
      - HADOOP_HOME=${HADOOP_HOME}
      - JAVA_HOME=${JAVA_HOME}
    networks:
      hadoop-net:
        aliases:
          - worker2
    depends_on:
      - master
    command: >
      sh -c "service ssh start &&
             $HADOOP_HOME/sbin/hadoop-daemon.sh start datanode &&
             $HADOOP_HOME/sbin/yarn-daemon.sh start nodemanager &&
             tail -f /dev/null"

networks:
  hadoop-net:
    driver: bridge
