version: '3.8'

services:
  hiveserver2:
    image: apache/hive:4.0.0-alpha-2
    container_name: hiveserver2
    environment:
      - SERVICE_NAME=hiveserver2
    ports:
      - "10000:10000"
      - "10002:10002"
    command: /opt/hive/bin/hive --service hiveserver2
